# Generated by Django 2.2.4 on 2019-10-06 08:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.CharField(blank=True, max_length=255)),
                ('car_model_id', models.CharField(blank=True, max_length=255)),
                ('state_id', models.TextField(blank=True)),
                ('dist_id', models.TextField(blank=True)),
                ('city_id', models.CharField(blank=True, max_length=50)),
                ('services_name', models.CharField(blank=True, max_length=255)),
                ('requested_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(default=0, max_length=5, verbose_name='0=requestto mechanic, 1 = request accept by mechanic, 2 = request reject by mechanic, 3 = services completed by mechanic')),
                ('mechanic_work_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mechanic_work_address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userProfile')),
            ],
        ),
    ]
