# Generated by Django 2.2.4 on 2019-10-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='mechanic_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='status',
            field=models.CharField(default=0, max_length=5, verbose_name='(STATUS)0=request to mechanic, 1 = request accept by mechanic, 2 = request reject by mechanic, 3 = services completed by mechanic'),
        ),
    ]
