# Generated by Django 2.2.4 on 2019-10-06 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191006_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='car_id',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='car_model_id',
        ),
        migrations.AddField(
            model_name='bookings',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Car'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='model_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Car_model'),
        ),
    ]
