# Generated by Django 2.2.4 on 2019-10-06 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191006_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='dist_id',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='state_id',
        ),
        migrations.AddField(
            model_name='bookings',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='dist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.Districts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.State'),
            preserve_default=False,
        ),
    ]
