# Generated by Django 2.2.4 on 2019-10-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191006_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='deleted_by_mechanic',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='bookings',
            name='deleted_by_user',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
