# Generated by Django 2.2.4 on 2019-10-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191006_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='car_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
