# Generated by Django 2.2.4 on 2019-10-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191007_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='address',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='car_number',
        ),
    ]
